# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1144, 656)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout.addWidget(self.line_5)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.webView = QtWebKit.QWebView(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webView.sizePolicy().hasHeightForWidth())
        self.webView.setSizePolicy(sizePolicy)
        self.webView.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.webView.setProperty("url", QtCore.QUrl(_fromUtf8("about:blank")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.horizontalLayout_2.addWidget(self.webView)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_2.addWidget(self.line_3)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(8, -1, 9, -1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_4.addWidget(self.label_8)
        self.line_7 = QtGui.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_4.addWidget(self.line_7)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.spinHexRobotNumber = QtGui.QSpinBox(self.centralwidget)
        self.spinHexRobotNumber.setMinimum(0)
        self.spinHexRobotNumber.setMaximum(10)
        self.spinHexRobotNumber.setProperty("value", 2)
        self.spinHexRobotNumber.setObjectName(_fromUtf8("spinHexRobotNumber"))
        self.verticalLayout_4.addWidget(self.spinHexRobotNumber)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_4.addWidget(self.label_10)
        self.spinHexAngle = QtGui.QSpinBox(self.centralwidget)
        self.spinHexAngle.setMinimum(-1)
        self.spinHexAngle.setMaximum(359)
        self.spinHexAngle.setProperty("value", -1)
        self.spinHexAngle.setObjectName(_fromUtf8("spinHexAngle"))
        self.verticalLayout_4.addWidget(self.spinHexAngle)
        self.label_11 = QtGui.QLabel(self.centralwidget)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_4.addWidget(self.label_11)
        self.spinHexAltitude = QtGui.QSpinBox(self.centralwidget)
        self.spinHexAltitude.setMinimum(7)
        self.spinHexAltitude.setProperty("value", 15)
        self.spinHexAltitude.setObjectName(_fromUtf8("spinHexAltitude"))
        self.verticalLayout_4.addWidget(self.spinHexAltitude)
        self.label_14 = QtGui.QLabel(self.centralwidget)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_4.addWidget(self.label_14)
        self.spinHexAltMult = QtGui.QSpinBox(self.centralwidget)
        self.spinHexAltMult.setSingleStep(1)
        self.spinHexAltMult.setProperty("value", 2)
        self.spinHexAltMult.setObjectName(_fromUtf8("spinHexAltMult"))
        self.verticalLayout_4.addWidget(self.spinHexAltMult)
        self.label_12 = QtGui.QLabel(self.centralwidget)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_4.addWidget(self.label_12)
        self.spinHexRadius = QtGui.QSpinBox(self.centralwidget)
        self.spinHexRadius.setMinimum(1)
        self.spinHexRadius.setMaximum(100)
        self.spinHexRadius.setProperty("value", 8)
        self.spinHexRadius.setObjectName(_fromUtf8("spinHexRadius"))
        self.verticalLayout_4.addWidget(self.spinHexRadius)
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_4.addWidget(self.label_13)
        self.spinHexWidthSize = QtGui.QSpinBox(self.centralwidget)
        self.spinHexWidthSize.setMinimum(1)
        self.spinHexWidthSize.setSingleStep(1)
        self.spinHexWidthSize.setProperty("value", 2)
        self.spinHexWidthSize.setObjectName(_fromUtf8("spinHexWidthSize"))
        self.verticalLayout_4.addWidget(self.spinHexWidthSize)
        self.btnHexToggleMaps = QtGui.QPushButton(self.centralwidget)
        self.btnHexToggleMaps.setObjectName(_fromUtf8("btnHexToggleMaps"))
        self.verticalLayout_4.addWidget(self.btnHexToggleMaps)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.line_8 = QtGui.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.horizontalLayout_5.addWidget(self.line_8)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_3.addWidget(self.label_9)
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout_3.addWidget(self.line_6)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.spinAngle = QtGui.QSpinBox(self.centralwidget)
        self.spinAngle.setMinimum(0)
        self.spinAngle.setMaximum(360)
        self.spinAngle.setSingleStep(5)
        self.spinAngle.setProperty("value", 90)
        self.spinAngle.setObjectName(_fromUtf8("spinAngle"))
        self.verticalLayout_3.addWidget(self.spinAngle)
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_3.addWidget(self.label_2)
        self.spinWidthSize = QtGui.QSpinBox(self.centralwidget)
        self.spinWidthSize.setMinimum(1)
        self.spinWidthSize.setMaximum(80)
        self.spinWidthSize.setSingleStep(1)
        self.spinWidthSize.setProperty("value", 2)
        self.spinWidthSize.setObjectName(_fromUtf8("spinWidthSize"))
        self.verticalLayout_3.addWidget(self.spinWidthSize)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_3.addWidget(self.label_4)
        self.spinAltitude = QtGui.QSpinBox(self.centralwidget)
        self.spinAltitude.setPrefix(_fromUtf8(""))
        self.spinAltitude.setMinimum(3)
        self.spinAltitude.setMaximum(200)
        self.spinAltitude.setProperty("value", 10)
        self.spinAltitude.setObjectName(_fromUtf8("spinAltitude"))
        self.verticalLayout_3.addWidget(self.spinAltitude)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_3.addWidget(self.label_5)
        self.spinSeconds = QtGui.QSpinBox(self.centralwidget)
        self.spinSeconds.setObjectName(_fromUtf8("spinSeconds"))
        self.verticalLayout_3.addWidget(self.spinSeconds)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_3.addWidget(self.label_6)
        self.comboWPSequence = QtGui.QComboBox(self.centralwidget)
        self.comboWPSequence.setObjectName(_fromUtf8("comboWPSequence"))
        self.comboWPSequence.addItem(_fromUtf8(""))
        self.comboWPSequence.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboWPSequence)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_3.addWidget(self.label_7)
        self.comboWPALT = QtGui.QComboBox(self.centralwidget)
        self.comboWPALT.setObjectName(_fromUtf8("comboWPALT"))
        self.comboWPALT.addItem(_fromUtf8(""))
        self.comboWPALT.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.comboWPALT)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnClearPaths = QtGui.QPushButton(self.centralwidget)
        self.btnClearPaths.setObjectName(_fromUtf8("btnClearPaths"))
        self.horizontalLayout_3.addWidget(self.btnClearPaths)
        self.btnGenRoute = QtGui.QPushButton(self.centralwidget)
        self.btnGenRoute.setObjectName(_fromUtf8("btnGenRoute"))
        self.horizontalLayout_3.addWidget(self.btnGenRoute)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout_2.addWidget(self.line_4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_2.addWidget(self.line)
        self.labelStatus = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Helvetica"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelStatus.setFont(font)
        self.labelStatus.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelStatus.setObjectName(_fromUtf8("labelStatus"))
        self.verticalLayout_2.addWidget(self.labelStatus)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1144, 23))
        self.menuBar.setNativeMenuBar(False)
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuMap = QtGui.QMenu(self.menuBar)
        self.menuMap.setObjectName(_fromUtf8("menuMap"))
        MainWindow.setMenuBar(self.menuBar)
        self.actionSave_polygon_shape = QtGui.QAction(MainWindow)
        self.actionSave_polygon_shape.setObjectName(_fromUtf8("actionSave_polygon_shape"))
        self.actionLoad_polygon_shape = QtGui.QAction(MainWindow)
        self.actionLoad_polygon_shape.setObjectName(_fromUtf8("actionLoad_polygon_shape"))
        self.actionReload_Map = QtGui.QAction(MainWindow)
        self.actionReload_Map.setObjectName(_fromUtf8("actionReload_Map"))
        self.actionExport_Route = QtGui.QAction(MainWindow)
        self.actionExport_Route.setObjectName(_fromUtf8("actionExport_Route"))
        self.actionExit_program = QtGui.QAction(MainWindow)
        self.actionExit_program.setObjectName(_fromUtf8("actionExit_program"))
        self.menuFile.addAction(self.actionSave_polygon_shape)
        self.menuFile.addAction(self.actionLoad_polygon_shape)
        self.menuFile.addAction(self.actionExit_program)
        self.menuMap.addAction(self.actionReload_Map)
        self.menuMap.addAction(self.actionExport_Route)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuMap.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Route Generator", None))
        self.label_8.setText(_translate("MainWindow", "Hexagon config", None))
        self.label.setText(_translate("MainWindow", "Robot number", None))
        self.label_10.setText(_translate("MainWindow", "Path angle", None))
        self.label_11.setText(_translate("MainWindow", "Altitude (mts)", None))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p>Alt (mts)<br/>multiplicator</p></body></html>", None))
        self.label_12.setText(_translate("MainWindow", "Radius (mts)", None))
        self.label_13.setText(_translate("MainWindow", "Cover width (mts)", None))
        self.btnHexToggleMaps.setText(_translate("MainWindow", "Toggle hex routes", None))
        self.label_9.setText(_translate("MainWindow", "Magnetic config", None))
        self.label_3.setText(_translate("MainWindow", "Path angle", None))
        self.spinAngle.setSuffix(_translate("MainWindow", " degrees", None))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>Cover width (mts)</p></body></html>", None))
        self.spinWidthSize.setSuffix(_translate("MainWindow", " mts", None))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>Altitude (mts)</p></body></html>", None))
        self.spinAltitude.setSuffix(_translate("MainWindow", " mts", None))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>Time to wait at WP<br/>In seconds</p></body></html>", None))
        self.spinSeconds.setSuffix(_translate("MainWindow", " seconds", None))
        self.label_6.setText(_translate("MainWindow", "WP sequence", None))
        self.comboWPSequence.setItemText(0, _translate("MainWindow", "Normal", None))
        self.comboWPSequence.setItemText(1, _translate("MainWindow", "Spaced", None))
        self.label_7.setText(_translate("MainWindow", "WP altitude type", None))
        self.comboWPALT.setItemText(0, _translate("MainWindow", "Follow Terrain", None))
        self.comboWPALT.setItemText(1, _translate("MainWindow", "Normal", None))
        self.btnClearPaths.setText(_translate("MainWindow", "Clear paths", None))
        self.btnGenRoute.setText(_translate("MainWindow", "Generate route", None))
        self.labelStatus.setText(_translate("MainWindow", "Status", None))
        self.menuFile.setTitle(_translate("MainWindow", "File&", None))
        self.menuMap.setTitle(_translate("MainWindow", "Map", None))
        self.actionSave_polygon_shape.setText(_translate("MainWindow", "Save polygon shape", None))
        self.actionLoad_polygon_shape.setText(_translate("MainWindow", "Load polygon shape", None))
        self.actionReload_Map.setText(_translate("MainWindow", "Reload Map", None))
        self.actionExport_Route.setText(_translate("MainWindow", "Export Route", None))
        self.actionExit_program.setText(_translate("MainWindow", "Exit", None))

from PyQt4 import QtWebKit
